SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;

SELECT NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, SUM(SALARY) SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
GROUP BY NVL(DEPT_TITLE, '부서없음');

SELECT JOB_NAME, ROUND(AVG(SALARY), 1) AVG_SALARY
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
GROUP BY JOB_NAME, JOB_CODE
ORDER BY JOB_CODE ;