-- [연습 문제]
-- 회원가입용 테이블 생성(USER_TEST)
-- 컬럼명 : USER_NO(회원번호) - 기본키(PK_USER_TEST), 
--         USER_ID(회원아이디) - 중복금지(UK_USER_ID),
--         USER_PWD(회원비밀번호) - NULL값 허용안함(NN_USER_PWD),
--         PNO(주민등록번호) - 중복금지(UK_PNO), NULL 허용안함(NN_PNO),
--         GENDER(성별) - '남' 혹은 '여'로 입력(CK_GENDER),
--         PHONE(연락처),
--         ADDRESS(주소),
--         STATUS(탈퇴여부) - NOT NULL(NN_STATUS), 'Y' 혹은 'N'으로 입력(CK_STATUS)
-- 각 컬럼의 제약조건에 이름 부여할 것
-- 각 컬럼에 주석 달기
-- 5명 이상 INSERT할 것

CREATE TABLE USER_TEST(
	USER_NO NUMBER CONSTRAINT PK_USER_TEST PRIMARY KEY,
	USER_ID VARCHAR2(20) CONSTRAINT UK_USER_ID UNIQUE,
	USER_PWD VARCHAR2(30) CONSTRAINT NN_USER_PWD NOT NULL,
	PNO VARCHAR2(14) CONSTRAINT NN_PNO NOT NULL CONSTRAINT UK_PNO UNIQUE,
	GENDER VARCHAR2(10) CONSTRAINT CK_GENDER CHECK( GENDER IN('남', '여') ),
	PHONE VARCHAR2(20),
	ADDRESS VARCHAR2(50),
	STATUS VARCHAR2(10) DEFAULT 'N' CONSTRAINT NN_STATUS NOT NULL 
											CONSTRAINT CK_STATUS CHECK( STATUS IN('Y', 'N') )
);

DROP TABLE USER_TEST;

COMMENT ON COLUMN USER_TEST.USER_NO IS '회원번호';
COMMENT ON COLUMN USER_TEST.USER_ID IS '회원아이디';
COMMENT ON COLUMN USER_TEST.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN USER_TEST.PNO IS '주민등록번호';
COMMENT ON COLUMN USER_TEST.GENDER IS '성별';
COMMENT ON COLUMN USER_TEST.PHONE IS '연락처';
COMMENT ON COLUMN USER_TEST.ADDRESS IS '주소';
COMMENT ON COLUMN USER_TEST.STATUS IS '탈퇴여부';

INSERT INTO USER_TEST VALUES
(1, 'USER01', 'PASS01', '950101-1234567', '남', '010-1234-5678', '서울시 송파구', 'N');
INSERT INTO USER_TEST VALUES
(2, 'USER02', 'PASS02', '950201-2124422', '여', '010-1422-5325', '서울시 서대문구', 'N');
INSERT INTO USER_TEST VALUES
(3, 'USER03', 'PASS03', '950301-3134232', '남', '010-7352-2436', '서울시 종로구', 'N');
INSERT INTO USER_TEST VALUES
(4, 'USER04', 'PASS04', '950401-4213422', '여', '010-2643-7435', '서울시 은평구', 'N');
INSERT INTO USER_TEST VALUES
(5, 'USER05', 'PASS05', '950501-1123423', '남', '010-8354-2178', '서울시 마포구', 'N');

INSERT INTO USER_TEST VALUES
(6, NULL, 'PASS06', '910501-1232332', '남', NULL, NULL, 'N');


SELECT * FROM USER_TEST;

DELETE FROM USER_TEST;

-- 테이블 주석 확인
SELECT * FROM USER_COL_COMMENTS
WHERE TABLE_NAME = 'USER_TEST';