CREATE TABLE MAJOR(
	MAJOR_NO NUMBER PRIMARY KEY,
	MAJOR_NM VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN MAJOR.MAJOR_NO IS '학과번호';
COMMENT ON COLUMN MAJOR.MAJOR_NM IS '학과명';

INSERT INTO MAJOR VALUES(1, '법학과');
INSERT INTO MAJOR VALUES(2, '국어국문학과');
INSERT INTO MAJOR VALUES(3, '수학과');
INSERT INTO MAJOR VALUES(4, '정치학과');
INSERT INTO MAJOR VALUES(5, '경영학과');

SELECT * FROM MAJOR;


CREATE TABLE STUDENT(
	STUDENT_ID NUMBER PRIMARY KEY,
	STUDENT_NAME VARCHAR2(20) NOT NULL,
	GENDER VARCHAR2(3) CHECK (GENDER IN ('남', '여')),
	BIRTH DATE,
	MAJOR_NO NUMBER REFERENCES MAJOR ON DELETE SET NULL
);

COMMENT ON COLUMN STUDENT.STUDENT_ID IS '학번';
COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '이름';
COMMENT ON COLUMN STUDENT.GENDER IS '성별';
COMMENT ON COLUMN STUDENT.BIRTH IS '생년월일';
COMMENT ON COLUMN STUDENT.MAJOR_NO IS '전공학과번호';

INSERT INTO STUDENT VALUES(1, '임성혁', '남', '19950516', 1);
INSERT INTO STUDENT VALUES(2, '차미영', '여', '19960206', 3);
INSERT INTO STUDENT VALUES(3, '최민식', '남', '19921123', 4);
INSERT INTO STUDENT VALUES(4, '전종서', '여', '19970717', 5);
INSERT INTO STUDENT VALUES(5, '김계란', '남', '19900809', 2);

SELECT * FROM STUDENT;

DROP TABLE MAJOR;

ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;