-- 1번 문제
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 2번 문제
SELECT STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD') DESC;

-- 3번 문제
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%'
AND SUBSTR(STUDENT_ADDRESS, 1, 3) IN('강원도', '경기도')
ORDER BY STUDENT_NAME;

-- 4번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD');

-- 5번 문제
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
AND TERM_NO = '200402'
ORDER BY POINT DESC;

-- 6번 문제
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT;
--ORDER BY STUDENT_NAME;

-- 7번 문제
SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_DEPARTMENT
NATURAL JOIN TB_CLASS;

-- 8번 문제
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
ORDER BY TO_NUMBER(TB_CLASS.DEPARTMENT_NO);

-- 9번 문제
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_DEPARTMENT
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
WHERE CATEGORY = '인문사회';

-- 10번 문제
SELECT STUDENT_NO "학번", STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 11번 문제
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 12번 문제
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE TB_GRADE.CLASS_NO = 'C2604100'
--AND SUBSTR(TERM_NO, 1, 4) = '2007'; -- 내 코드
AND TERM_NO LIKE '2007%'; -- 강사님 코드

-- 13번 문제
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

-- 14번 문제
SELECT STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT
LEFT JOIN TB_PROFESSOR ON(PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE TB_STUDENT.DEPARTMENT_NO = '020';

-- 15번 문제
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", DEPARTMENT_NAME "학과", ROUND(AVG(POINT), 2) "평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING ROUND(AVG(POINT), 2) >= 4;

-- 16번 문제
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_GRADE
JOIN TB_CLASS USING(CLASS_NO)
WHERE DEPARTMENT_NO = '034'
AND CLASS_TYPE = '전공선택'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 17번 문제
SELECT STUDENT_NAME, STUDENT_ADDRESS 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '038';

-- 18번 문제
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '001'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- 19번 문제
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT), 1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CLASS_TYPE = '전공선택'
AND CATEGORY = '자연과학'
GROUP BY ROLLUP(DEPARTMENT_NAME, CLASS_NAME)
HAVING NVL(CLASS_NAME, ' ') = ' '
AND NVL(DEPARTMENT_NAME, NULL) IS NOT NULL
ORDER BY 1;