CREATE TABLE WARRIOR(
	WARRIOR_NO NUMBER PRIMARY KEY,
	WARRIOR_NAME VARCHAR(20) NOT NULL,
	WARRIOR_LEVEL NUMBER DEFAULT(1) NOT NULL,
	WARRIOR_EXP NUMBER DEFAULT(0) NOT NULL,
	MAX_HP NUMBER DEFAULT(100) NOT NULL,
	HP NUMBER DEFAULT(100) NOT NULL,
	ATTACK NUMBER DEFAULT(5) NOT NULL,
	STAT_POINT NUMBER DEFAULT(1) NOT NULL,
	GOLD NUMBER DEFAULT(20) NOT NULL,
	ISALIVE VARCHAR(1) DEFAULT('Y') CHECK(ISALIVE IN('Y', 'N')) NOT NULL,
	CREATE_DATE	DATE	DEFAULT SYSDATE NOT NULL,
	WARRIOR_DEL_FL CHAR(1)	DEFAULT 'N'	NOT NULL,
	MEMBER_NO NUMBER REFERENCES "MEMBER" ON DELETE CASCADE
);

COMMENT ON COLUMN WARRIOR.WARRIOR_NO IS '캐릭터 번호';
COMMENT ON COLUMN WARRIOR.WARRIOR_NAME IS '캐릭터 이름';
COMMENT ON COLUMN WARRIOR.WARRIOR_LEVEL IS '레벨';
COMMENT ON COLUMN WARRIOR.WARRIOR_EXP IS '경험치';
COMMENT ON COLUMN WARRIOR.MAX_HP IS '최대체력';
COMMENT ON COLUMN WARRIOR.HP IS '현재체력';
COMMENT ON COLUMN WARRIOR.ATTACK IS '공격력';
COMMENT ON COLUMN WARRIOR.STAT_POINT IS '능력치 포인트';
COMMENT ON COLUMN WARRIOR.GOLD IS '골드';
COMMENT ON COLUMN WARRIOR.ISALIVE IS '생존여부';
COMMENT ON COLUMN WARRIOR.CREATE_DATE IS '캐릭터 생성 일자';
COMMENT ON COLUMN WARRIOR.WARRIOR_DEL_FL IS '삭제여부';
COMMENT ON COLUMN WARRIOR.MEMBER_NO IS 'WARRIOR 소유 회원 번호';

CREATE SEQUENCE SEQ_WARRIOR_NO NOCACHE;

INSERT INTO WARRIOR VALUES(
	SEQ_WARRIOR_NO.NEXTVAL,
	'광전사',
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	DEFAULT,
	1
);

-- 무기 인벤토리
CREATE TABLE WEAPON_LIST(
	WEAPON_NO NUMBER PRIMARY KEY,
	WEAPON_NAME VARCHAR(50) NOT NULL,
	WEAPON_ATTACK NUMBER NOT NULL,
	AVALIABLE_LEVEL NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	EQUIP_FL VARCHAR2(1) DEFAULT('N') CHECK(EQUIP_FL IN('Y', 'N')) NOT NULL,
	SELL_FL VARCHAR2(1) DEFAULT('N') CHECK(SELL_FL IN('Y', 'N')) NOT NULL,
	WARRIOR_NO NUMBER REFERENCES WARRIOR ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_WEAPON_NO NOCACHE;

COMMENT ON COLUMN WEAPON_LIST.WEAPON_NO IS '무기 번호';
COMMENT ON COLUMN WEAPON_LIST.WEAPON_NAME IS '무기 이름';
COMMENT ON COLUMN WEAPON_LIST.WEAPON_ATTACK IS '무기 공격력';
COMMENT ON COLUMN WEAPON_LIST.AVALIABLE_LEVEL IS '장착 가능 레벨';
COMMENT ON COLUMN WEAPON_LIST.PRICE IS '가격';
COMMENT ON COLUMN WEAPON_LIST.EQUIP_FL IS '장착 여부';
COMMENT ON COLUMN WEAPON_LIST.SELL_FL IS '판매 여부';
COMMENT ON COLUMN WEAPON_LIST.WARRIOR_NO IS '무기 인벤토리 소유 WARRIOR';

INSERT INTO WEAPON_LIST VALUES(SEQ_WEAPON_NO.NEXTVAL, '기본 검', 3, 1, 5, 'Y', 'N', 1);
INSERT INTO WEAPON_LIST VALUES(SEQ_WEAPON_NO.NEXTVAL, '날카로운 검', 5, 1, 10, 'N', 'N', 1);
INSERT INTO WEAPON_LIST VALUES(SEQ_WEAPON_NO.NEXTVAL, '검붉은 검', 8, 1, 20, 'N', 'N', 1);

-- 물약 인벤토리
CREATE TABLE POTION_LIST(
	POTION_NO NUMBER PRIMARY KEY,
	POTION_NAME VARCHAR(30) NOT NULL,
	HEAL NUMBER NOT NULL,
	QUANTITY NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	WARRIOR_NO NUMBER REFERENCES WARRIOR ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_POTION_NO NOCACHE;

COMMENT ON COLUMN POTION_LIST.POTION_NO IS '물약 번호';
COMMENT ON COLUMN POTION_LIST.POTION_NAME IS '물약 이름';
COMMENT ON COLUMN POTION_LIST.HEAL IS '치유량';
COMMENT ON COLUMN POTION_LIST.HEAL IS '치유량';
COMMENT ON COLUMN POTION_LIST.QUANTITY IS '수량';
COMMENT ON COLUMN POTION_LIST.WARRIOR_NO IS '물약 인벤토리 소유 WARRIOR';

INSERT INTO POTION_LIST VALUES(
	SEQ_POTION_NO.NEXTVAL,
	'하급 체력 물약',
	20,
	5,
	3,
	1
);

COMMIT;






------- 조회 모음

SELECT * FROM WARRIOR;
SELECT * FROM WEAPON_LIST;
SELECT * FROM POTION_LIST;

------------- 삭제 모음

DROP TABLE POTION_LIST;
DROP TABLE WEAPON_LIST;
DROP TABLE WARRIOR;

DROP SEQUENCE SEQ_WARRIOR_NO;
DROP SEQUENCE SEQ_WEAPON_NO;
DROP SEQUENCE SEQ_POTION_NO;